### ISSUE TITLE
FileNotFoundError when the specified 'output_dir' does not already exist.

### ISSUE THREAD

**Issue by Evans-Onyango** [adjtomo/pysep#109]
An error regarding the existence of pysep.log shows up when the 'output_dir' specified while running pysep does not pre-exist.
![Screenshot2](https://user-images.githubusercontent.com/31168277/229257656-75491bfe-0224-4966-9978-a46c696be0c0.png)

**Comment by bch0w** [comment]
Hi @Evans-Onyango, thanks for bringing this up (@aakash10gupta pointed this out to me in an email as well)

This is happening because the logger is trying to set up a file before the output directory is created. To get around this for now you can manually create your output directory, but I will push a fix for this asap.

**Comment by bch0w** [comment]
Hi @Evans-Onyango, I patched this bug in https://github.com/adjtomo/pysep/commit/01492f5e8b8b0227823a03150a41b5202cfdeaf4, should be working in the latest `devel` branch. Can you give it a shot and see if that fixes it?

**Comment by Evans-Onyango** [comment]
Will do. Thank you!

**Comment by bch0w** [comment]
Closing as this has been fixed in the latest version. Please re-open if you are still encountering this issue!
