### ISSUE TITLE
empty defaults for event_depth_km and event_depth_mag

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#71]
In cases where the event depth and magnitude are unknown, it would be nice to allow pysep to proceed with record section plotting. Is it possible to allow empty [] arguments? It seems like entering a default like 1 or 5 could lead to problems down the road. Thanks!

**Comment by aakash10gupta** [comment]
Probably this can be a separate issue but I thought I would start here.

When `event_depth_km = None` and `event_magnitude = None` and `plot_files = map` or `plot_files = all`, running the data download leads to an error probably because the plotting utility `plot_source_receiver_map` function needs these. A side note that maps and record sections have wrong depth and magnitude in their titles when dummy event details are provided.

Maybe a check can be added such that if `event_depth_km = None` and/or `event_magnitude = None` and if `plot_files = map` or `plot_files = all` then a warning is generated, the map utility is not called, but no error is generated.

**Comment by bch0w** [comment]
@aakash10gupta Thanks for catching that, in [23e208e](https://github.com/adjtomo/pysep/commit/23e208ee591a8861367f56533329570393a01aab) I removed the mapping function dependence on depth and magnitude information.

Additionally in #102, rather than checking all options I just threw on a general try-except around both plotting functions to allow that portion to fail since it is not critical for the remainder of the workflow. Hopefully that's enough to keep things from crashing.

> A side note that maps and record sections have wrong depth and magnitude in their titles when dummy event details are provided.

Are the 'wrong' values here the dummy values? If so then they are technically the 'right' values. Best to set these as None if you don't want to see the dummy values in the title.

**Comment by aakash10gupta** [comment]
> Are the 'wrong' values here the dummy values? If so then they are technically the 'right' values. Best to set these as None if you don't want to see the dummy values in the title.

Yes, the 'wrong' values are the dummy values. I was having to use the dummy values since I wanted the map.

It looks like with the latest update I cannot get a map if the event depth and magnitude are not provided. Is that intended? Does that also mean I cannot use the plot_source_receiver_map utility to plot the map because the event.xml also does not have the event depth and magnitude information?

**Comment by bch0w** [comment]
Looks like the log messages show that this is an ObsPy issue if you set both to None.

```bash
[2023-03-09 09:47:31] - pysep - INFO: plotting source receiver map
[2023-03-09 09:47:31] - pysep - DEBUG: setting projection local due to max src-rcv distance of 299.3261734083576km
/opt/miniconda3/envs/pysep/lib/python3.11/site-packages/obspy/core/event/catalog.py:680: UserWarning: Event 'smi:local/1ae48bc2-186c-4727-a90b-99b5331e1459' does not have a magnitude and will not be plotted.
  warnings.warn(msg)
```

I tried with just magnitude only but ObsPy needs depth as well. Likely because it colors and sizes by depth and magnitude (even when plotting one event), so not providing these values breaks it.

So yes, you won't be able to plot maps without a valid depth and magnitude. Probably in the future we can get around this by not using the Catalog plot function but I think it's low priority if maps work otherwise.

If you'd like to fix this, I can suggest the edits to make for a PR, but PySEP needs depth to calculate the TauP arrivals too so I think the most efficient route is to put in values for the depth and magnitude.
