### ISSUE TITLE
Pysep throws error for legal obspy pass-through argument value

### ISSUE THREAD

**Issue by mchristoffersen** [adjtomo/pysep#93]
In Pysep if remove_response is set to true there is an assert statement which enforces that the water_level argument cannot be None (pysep.py, lines 503-508), however water_level=None is a legal argument to Obspy's remove_response method, which Pysep's water_level argument is passed through too.

**Comment by bch0w** [comment]
Good catch! Thanks @mchristoffersen, I just removed that hard restriction in https://github.com/adjtomo/pysep/commit/ee658bd76016450c09e040095891ee3174e5125a (devel branch)


Just as an aside, I feel like ObsPy's documentation could be a little more clear with that since they list in their docstring

> water_level ([float](https://docs.python.org/3/library/functions.html#float)) – Water level for deconvolution.

**Comment by aakash10gupta** [comment]
Looks like `water_level = None` is a valid option now for pysep. This issue can be closed.
