### ISSUE TITLE
seismogram normalization error

### ISSUE THREAD

**Issue by aakash10gupta** [adjtomo/pysep#99]
When the `sort_by` option is set to `abs_distance` or `abs_azimuth` and the `scale_by` option is set to `normalize`, the seismograms seem to have an inverted value for each sample i.e. a positive value becomes negative and vice versa.

**Comment by bch0w** [comment]
Thanks for catching this. This arose due to #75 where I was switching the behavior of `abs` and `abs_*_r` sorting to have things more intuitive. 

Just to explain why this happened, when plotting absolute values, the natural y-axis has smallest values on the bottom, with 0 at the origin. However in #75 we wanted to make the default behavior to have smallest values at the top of the figure, so I threw in an `invert_yaxis()` to get that behavior without considering this would also flip the seismograms. 

https://github.com/adjtomo/pysep/blob/devel/pysep/recsec.py#L1811

I'll have to think of a different way of changing the sort order that preserves the seismogram polarities.

**Comment by bch0w** [comment]
This is addressed in #100

**Comment by aakash10gupta** [comment]
This issue seems resolved with the latest update. Thanks.
